server:
  #端口号
  port: 8095
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:E:/sqlitedb/ip-address.sqlite3
    username:
    password: 123456
    ### sqlite需要自己配置连接方式
  jpa:
    database-platform: com.ts.address.config.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  # 后缀名
    content-type: text/html
    enabled: true
    cache: false # 缓存配置
    template-loader-path: classpath:/templates/ # 模板加载路径 按需配置
    charset: UTF-8 # 编码格式
    settings:
      number_format: '0.##'   #数字格式化, 无小数点

  mail:
    host: smtp.qq.com # 发送邮件服务器
    username: 597429743@qq.com # 发送邮件的邮箱地址
    password:  yvotxizwhumnbdcd # 客户端授权码, 不是邮箱密码, 这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 # 端口号465或587
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

# 扩张配置
balloon:
  springboot:
    enabled: true
  security:
    enabled: false
  mail:
    enabled: true
    from: 597429743@qq.com # 邮件发送人
    to: 977626570@qq.com,liyc@thinking-star.com,thomaschen750215@126.com,thinkingstar2020@126.com # 收件人
    # to: 977626570@qq.com
    subject: WUHAN IP HOSTNAME # 邮件主题



